### ISSUE TITLE
AttributeError: module 'yake' has no attribute 'KeywordExtractor'

### ISSUE THREAD

**Issue by KevinFiorentin** [LIAAD/yake#36]
Hi, I'm trying to use yake on python. I installed it using pip. I copy/paste the code from readme into my script file and got the following error:

```
Traceback (most recent call last):
  File "./yake.py", line 57, in <module>
    main()
  File "./yake.py", line 16, in main
    tmp = assuming_default_parameters(data)
  File "./yake.py", line 26, in assuming_default_parameters
    kw_extractor = yake.KeywordExtractor()
AttributeError: module 'yake' has no attribute 'KeywordExtractor'
```

Could someone help me?

**Comment by KevinFiorentin** [comment]
OMG I wish I could delete this. I found the error.
