### ISSUE TITLE
UnboundLocalError: local variable 'block_of_word_obj' referenced before assignment

### ISSUE THREAD

**Issue by vgoklani** [LIAAD/yake#7]
What does this error mean?

	Traceback (most recent call last):
	  File "/root/src/streamer/consumer.py", line 188, in callback
	    keywords = set([_[1].upper() for _ in self._kw_extractor.extract_keywords(message["text"])])
	  File "/opt/conda/lib/python3.7/site-packages/yake/yake.py", line 52, in extract_keywords
	    dc = DataCore(text=text, stopword_set=self.stopword_set, windowsSize=self.windowsSize, n=self.n)
	  File "/opt/conda/lib/python3.7/site-packages/yake/datarepresentation.py", line 30, in __init__
	    self._build(text, windowsSize, n)
	  File "/opt/conda/lib/python3.7/site-packages/yake/datarepresentation.py", line 93, in _build
	    if len(block_of_word_obj) > 0:
	UnboundLocalError: local variable 'block_of_word_obj' referenced before assignment

**Comment by vitordouzi** [comment]
Probably the error occurs when an empty text (or sentence) is passed. I changed the code to include this case and commit the new version.

Can you try again with this version?

Thanks for the error report.
